user_mgmt_system/models.py
from user_mgmt_system import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), nullable = False, unique=True, index=True)
    gender = db.Column(db.String(7), nullable=False)
    user_type = db.Column(db.String(50), nullable=False)
    password_hash = db.Column(db.String(128))

    def __init__(self, name, email,gender, user_type, password):
        self.name = name
        self.email = email
        self.gender = gender
        self.user_type = user_type
        self.password_hash = generate_password_hash(password)

    def __repr__(self):
        return f"Name: {self.name}"

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

user_mgmt_system/users/forms.py
# users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField, ValidationError
from wtforms.validators import DataRequired, Email, EqualTo
from user_mgmt_system.models import User

class RegistrationForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    gender = SelectField('Gender', validators=[DataRequired()], choices=[('male','Male'),('female','Female')], coerce=str)
    user_type = SelectField('Type of User', validators=[DataRequired()], choices=[('admin','Administrator'),('general','General')], coerce=str)
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email is already registered!')

class EditUserForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    user_type = SelectField('Type of User', validators=[DataRequired()], choices=[('admin','Administrator'),('general','General')], coerce=str)
    submit = SubmitField('Save Changes')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

user_mgmt_system/__init__.py
# user_mgmt_system/__init__.py

# imports
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

# app init
app = Flask(__name__)
app.config['SECRET_KEY'] = 'mysecret'

# DB setup
ENV = 'dev'

if ENV == 'dev':
    app.debug = True
    app.config['SQLALCHEMY_DATABASE_URI'] = "postgresql://postgres:1234@postgres-users/users"
else:
    app.debug = False
    app.config['SQLALCHEMY_DATABASE_URI'] = "postgres://pdogkmcqkaiono:88b8a26a9d4a00ff5a9acacfa984258051e83bbcb5e220e28ec9ed266f453a63@ec2-3-226-231-4.compute-1.amazonaws.com:5432/d4kmrclpsjjhm9"



app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

# login configs
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'

# register blueprints
from user_mgmt_system.core.views import core
from user_mgmt_system.users.views import users
from user_mgmt_system.error_pages.error_handler import error_pages

app.register_blueprint(core)
app.register_blueprint(users)
app.register_blueprint(error_pages)

user_mgmt_system/core/__init__.py
# core/__init__.py

user_mgmt_system/core/views.py
from flask import render_template, Blueprint
from user_mgmt_system import db, app

core = Blueprint('core', __name__)

# --------- HOME --------- #
@core.route('/')
def index():
    db.create_all()
    return render_template('index.html')


# --------- ABOUT --------- #
@core.route('/about')
def info():
    return render_template('about.html')


# --------- CONTACT --------- #
@core.route('/contact')
def contact():
    return render_template('contact.html')

user_mgmt_system/users/__init__.py
# users/__init__.py

user_mgmt_system/users/views.py
from flask import render_template, request, url_for, redirect, Blueprint, abort, flash
from flask_login import login_user, logout_user, login_required, current_user
from user_mgmt_system import db
from user_mgmt_system.models import User
from user_mgmt_system.users.forms import RegistrationForm, LoginForm, EditUserForm

users = Blueprint('users', __name__)

# --------- USERS --------- #
@users.route('/users', methods=['GET','POST'])
def view_users():
    page = request.args.get('page',1,type=int)
    all_users = User.query.order_by(User.id.asc()).paginate(page=page, per_page=5, error_out=False)
    users = User.query.all()
    next_url = url_for('users.view_users', page=all_users.next_num) if all_users.has_next else None
    prev_url = url_for('users.view_users', page=all_users.prev_num) if all_users.has_prev else None
    return render_template('users.html', users=users, all_users=all_users.items, next_url=next_url, prev_url=prev_url)


# --------- REGISTER --------- #
@users.route('/register', methods=['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(name = form.name.data,
                    email = form.email.data,
                    gender = form.gender.data,
                    user_type = form.user_type.data,
                    password = form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


# --------- LOG IN --------- #
@users.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash("The email you entered is not registered!")
        else:
            if user.check_password(form.password.data):
                login_user(user)
                next = request.args.get('next')
                if next == None or not next[0] == '/':
                    next = url_for('core.index')
                return redirect(next)
            else:
                flash("The password you entered is invalid")
    return render_template('login.html', form=form)


# --------- LOG OUT --------- #
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/<int:user_id>/update', methods=["GET","POST"])
@login_required
def edit(user_id):
    form = EditUserForm()
    user = User.query.get(user_id)
    if form.validate_on_submit():
        user.name = form.name.data
        user.email = form.email.data
        user.user_type = form.user_type.data
        db.session.commit()
        return redirect(url_for('core.index'))

    elif request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.user_type.data = user.user_type
    return render_template('edit_user.html', form=form, user=user)

# --------- DELETE --------- #
@users.route('/<int:user_id>/delete', methods=["GET","POST"])
@login_required
def delete(user_id):
    user = User.query.get(user_id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('core.index'))

user_mgmt_system/templates/about.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="jumbotron mt-4">
      <h1 class="text-center">What You Can Do</h1>
      <hr>
      <div class="card-deck">
        <div class="card text-center">
          <div class="card-header">
            <h5 class="card-title">Create...</h5>
          </div>
          <div class="card-body">
            <p>
              a new user by simply entering the name, email and password and clicking "register".
            </p>
          </div>
        </div>

        <div class="card text-center">
          <div class="card-header">
            <h5 class="card-title">Read...</h5>
          </div>
          <div class="card-body">
            <p>
              the contents of your database by first logging in and going to the users page.
              You will see a list of all the users registered with you.
            </p>
          </div>
        </div>

        <div class="card text-center">
          <div class="card-header">
            <h5 class="card-title">Update...</h5>
          </div>
          <div class="card-body">
            <p>
              any user using the edit button associated with the user you wish to edit. Once you're
              satisfied with the editing, submit the new information.
            </p>
          </div>
        </div>

        <div class="card text-center">
          <div class="card-header">
            <h5 class="card-title">Delete...</h5>
          </div>
          <div class="card-body">
            <p>
              any user by clicking the delete button adjacent to the user you wish to delete and
              confirming your action.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

user_mgmt_system/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Portal</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  </head>

  <body>
    <header>
      <nav id="main-nav" class="navbar navbar-expand-sm navbar-dark bg-primary">
        <div class="container">
          <h1><a href="{{ url_for('core.index') }}" class="navbar-brand">Users Portal</a></h1>
          <button type="button" class="navbar-toggler text-light" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse my-2" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item m-2"><a href="{{ url_for('core.index') }}" class="nav-link text-light">Home</a></li>
              <li class="nav-item m-2"><a href="{{ url_for('core.info') }}" class="nav-link text-light">About</a></li>
              <li class="nav-item m-2"><a href="{{ url_for('core.contact') }}" class="nav-link text-light">Contact</a></li>
              <li class="nav-item m-2"><a href="{{ url_for('users.view_users') }}" class="nav-link text-light">Users</a></li>
              {% if current_user.is_authenticated %}
              <li class="nav-item m-2"><a href="{{ url_for('users.logout') }}" class="nav-link text-light btn btn-outline-danger btn-sm">Logout</a></li>
              {% else %}
              <li class="nav-item m-2"><a href="{{ url_for('users.login') }}" class="nav-link text-light btn btn-outline-blue btn-sm">Login</a></li>
              {% endif %}
              <li class="nav-item m-2"><a href="{{ url_for('users.register') }}" class="nav-link text-light btn btn-blue btn-sm">Register</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    {% if current_user.is_authenticated %}
    <div class="bg-primary">
      <div class="container py-1 text-right">
        <p class="lead text-white"> Welcome {{ current_user.name.split()[0] }} </p>
      </div>
    </div>
    {% endif %}

    {% block content %}

    {% endblock %}

    <!-- FOOTER -->
    <footer class="bg-dark text-white text-center py-5">
      <p class="m-0">
        Copyright &copy; <span id="year"></span> User Portal
      </p>
    </footer>

  </body>
  <script type="text/javascript" src="static/js/jquery.js"></script>
  <script type="text/javascript" src="static/js/bootstrap.bundle.min.js"></script>
  <script type="text/javascript" src="static/js/all.js"></script>

  <script type="text/javascript">
    // Get the current year for the copyright text
    $('#year').text(new Date().getFullYear());

  </script>
</html>

user_mgmt_system/templates/contact.html
{% extends "base.html" %}
{% block content %}
  <section id="contact">
    <div class="container">
      <div class="row my-3">
        <div class="col-md-4">
          <div id="contact-card" class="card mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-md-3 pt-3">
                  <span class="fas fa-map-marked-alt fa-2x"></span>
                </div>
                <div class="col-md-9">
                  <h4>Location</h4>
                  <p>21st Street, New York, NY 432097</p>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3 pt-3">
                  <span class="fas fa-envelope-square fa-2x"></span>
                </div>
                <div class="col-md-9">
                  <h4>Email</h4>
                  <p>info@example.com</p>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3 pt-3">
                  <span class="fas fa-phone-alt fa-2x"></span>
                </div>
                <div class="col-md-9">
                  <h4>Phone</h4>
                  <p>+254 720 000 000</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-8">
          <div class="card mb-3">
            <div class="card-body">
              <form action="{{ url_for('core.index') }}" method="post">
                <h3 class="mb-3">Get In Touch</h3>
                <div class="form-group">
                  <label for="name">Name</label>
                  <input type="text" class="form-control">
                </div>
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" class="form-control">
                </div>
                <div class="form-group">
                  <label for="subject">Subject</label>
                  <input type="text" class="form-control">
                </div>
                <div class="form-group">
                  <label for="message">Message</label>
                  <textarea class="form-control"></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Send Message</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

user_mgmt_system/templates/edit_user.html
{% extends "base.html" %}
{% block content %}
<section id="edit">
  <div class="row">
    <div id="login-band" class="d-none d-lg-block col-lg-6">

    </div>
    <div class="col-md-8 col-lg-6 offset-md-2 offset-lg-0">
      <div class="container p-5">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Update Your Account</h4>
          </div>
          <div class="card-body">
            <form method="POST">
              {{ form.hidden_tag() }}
              <div class="form-group">
                {{ form.name.label() }}
                {{ form.name( class="form-control" ) }}
              </div>
              <div class="form-group">
                {{ form.email.label() }}
                {{ form.email( class="form-control" ) }}
              </div>
              <div class="form-group">
                {{ form.user_type.label() }}
                {{ form.user_type( class="form-control" ) }}
              </div>
              {{ form.submit( class="btn btn-block btn-primary" ) }}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

user_mgmt_system/templates/index.html
{% extends "base.html" %}
{% block content %}
<section id="hero" class="bg-primary">
  <div class="container">
    <div class="row">
      <div id="heroText" class="col-md-6 p-3 d-flex flex-column justify-content-center">
        <h1 class="text-light-1 mb-2">An Easier Way To Manage Your Users</h1>
        <h4 class="text-light-2 mb-4">We are a team of web developers specialised in user management</h4>
        <a href="{{ url_for('users.register') }}" class="btn btn-blue text-white">Learn More</a>
      </div>
      <div class="col-md-6 p-3">
        <img src="static/img/hero-img.png" class="img-fluid" alt="">
      </div>
    </div>
  </div>
</section>
{% endblock %}

user_mgmt_system/templates/login.html
{% extends "base.html" %}
{% block content %}
<section id="login">
  <div class="row">
    <div id="login-band" class="d-none d-inline-block col-md-6"></div>
    <div class="col-md-6">
      <div class="container p-5">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Login</h4>
          </div>
          <div class="card-body">
            <form method="POST">
              {{ form.hidden_tag() }}
              <div class="form-group mb-5">
                {{ form.email.label() }}
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <span class="fas fa-envelope"></span>
                    </div>
                  </div>
                  {{ form.email( class="form-control") }}
                </div>
              </div>

              <div class="form-group mb-5">
                {{ form.password.label() }}
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <span class="fas fa-lock"></span>
                    </div>
                  </div>
                  {{ form.password( class="form-control" ) }}
                </div>
              </div>
              {{ form.submit( class="btn btn-block btn-primary" ) }}
            </form>
            <p class="text-center mt-3">
              <small>Have no account?
                <a href="{{ url_for('users.register') }}" class="text-warning">Register</a>
              </small>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

user_mgmt_system/templates/register.html
{% extends "base.html" %}
{% block content %}
<section id="register">
  <div class="row">
    {% if current_user.is_authenticated %}
    <div class="container">
      <div class="py-5">
        <p>{{ current_user.name.split()[0] }}, you have already regitered.</p>
      </div>
    </div>
    {% else %}
    <div id="login-band" class="d-none d-lg-block col-lg-6">

    </div>

    <div class="col-md-8 col-lg-6 offset-md-2 offset-lg-0">
      <div class="container p-5">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Register</h4>
          </div>
          <div class="card-body">
            <form method="POST">
              {{ form.hidden_tag() }}
              <div class="row mb-2">
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.name.label() }}
                    {{ form.name( class="form-control" ) }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.email.label() }}
                    {{ form.email( class="form-control" ) }}
                  </div>
                </div>
              </div>

              <div class="row mb-2">
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.gender.label() }}
                    {{ form.gender( class="form-control" ) }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.user_type.label() }}
                    {{ form.user_type( class="form-control" ) }}
                  </div>
                </div>
              </div>

              <div class="row mb-2">
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.password.label() }}
                    {{ form.password( class="form-control" ) }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.pass_confirm.label() }}
                    {{ form.pass_confirm( class="form-control" ) }}
                  </div>
                </div>
              </div>
              {{ form.submit( class="btn btn-block btn-primary" ) }}
            </form>
            <p class="text-center mt-3">
              <small>Already have an account?
                <a href="{{ url_for('users.login') }}" class="text-warning">Sign in</a>
              </small>
            </p>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</section>
{% endblock %}

user_mgmt_system/templates/users.html
{% extends "base.html" %}
{% block content %}
  <div id="user_table" class="container">
    <table class="table table-striped">
      <thead>
        {% if users|length == 0 %}
        <div class="pt-4">
          <p class="lead m-0">There are no users registered yet</p>
        </div>
        {% else %}

        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Gender</th>
          <th>Type of User</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for user in all_users %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user.name }}</td>
          <td>{{ user.email }}</td>
          <td>{{ user.gender }}</td>
          <td>{{ user.user_type }}</td>
          {% if current_user.user_type == 'admin' or current_user.email == user.email %}
          <td>
            <a class="btn btn-danger btn-sm text-white mr-2" data-toggle="modal" data-target="#delModal">
              Delete
            </a>
            <a class="btn btn-warning btn-sm text-white" href="/{{ user.id }}/update">
              Edit
            </a>
          </td>

          <!-- DELETE MODAL -->
          <div id="delModal" class="modal">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Delete User?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Are you sure you want to delete this user?</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  <form action="/{{ user.id }}/delete">
                    <input type="submit" class="btn btn-danger" value="Delete">
                  </form>
                </div>
              </div>
            </div>
          </div>
          {% else %}
          <td>
            <a class="btn btn-danger btn-sm text-white disabled mr-2" data-toggle="modal" data-target="#delModal">
              Delete
            </a>
            <a class="btn btn-warning btn-sm text-white disabled" href="/{{ user.id }}/update">
              Edit
            </a>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
        {% endif %}
      </tbody>
    </table>



    <nav>
      <ul class="pagination pagination-sm">
        {% if prev_url %}
        <li class="page-link active disabled">
          <a href="{{ prev_url }}" class="page-link">
            <span class="fas fa-angle-double-left"></span>
          </a>
        </li>
        {% endif %}
        {% if next_url %}
        <li class="page-link">
          <a href="{{ next_url }}" class="page-link">
            <span class="fas fa-angle-double-right"></span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
{% endblock %}